# Streamlit Configuration
[server]
# Server settings
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# App theme
base="dark"
primaryColor="#9700ff"
